"""Update Tree model with more attributes

Revision ID: 1b71dc5caa2f
Revises: f2b20b1f64a6
Create Date: 2024-12-01 13:40:07.477484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b71dc5caa2f'
down_revision = 'f2b20b1f64a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('planted_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('planted_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
